<Panel>:
    canvas:
        Color:
            rgba: 1,1,1,1
        Rectangle:
            pos: self.pos
            size: self.size

<ScrollView>:
    do_scroll_x: False
    do_scroll_y: True
    scroll_wheel_distance: 120
    bar_width: 14
    bar_margin: 6
    bar_color: 255/255, 255/255, 255/255, 0.8
    bar_inactive_color:255/255, 255/255, 255/255, 0.4

<VocabGrid>:
    padding:dp(5),dp(5),dp(25),dp(5)


